<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) :?>
<form action="<?php echo $this->getFormAction(); ?>" id="testimonialForm" method="post" class="scaffold-form">
    <div class="fieldset">
        <p class="required"><?php echo Mage::helper('sk_testimonials')->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('sk_testimonials')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('sk_testimonials')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var testimonialForm = new VarienForm('testimonialForm', true);
//]]>
</script>
<?php endif; ?>